# Generated by Django 3.1.5 on 2021-01-09 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_auto_20210109_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='', upload_to=''),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
