# Generated by Django 3.1.5 on 2021-01-10 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0005_delete_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/%Y'),
        ),
    ]
