# Generated by Django 3.1.5 on 2021-01-11 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0007_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default='images/users/IMG_20200602_120716_501.jpg', upload_to='images/users'),
        ),
    ]
