# Generated by Django 3.1.5 on 2021-01-11 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0009_auto_20210111_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='text',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
