# Generated by Django 3.1.5 on 2021-01-11 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0010_userprofile_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Профиль', 'verbose_name_plural': 'Профили'},
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='text',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(upload_to='images/users', verbose_name='Изображение'),
        ),
    ]
