# Generated by Django 3.1.5 on 2021-01-11 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0011_auto_20210111_2034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='avatar',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='text',
            field=models.CharField(default='none', max_length=250),
        ),
    ]
